sudo: required
services:
  - docker

before_install:
  - docker build -t lavisht22/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lavisht22/react-test npm run test -- --coverage

after_success:
  - docker build -t lavisht22/multi-client ./client
  - docker build -t lavisht22/multi-nginx ./nginx
  - docker build -t lavisht22/multi-server ./server
  - docker build -t lavisht22/multi-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push lavisht22/multi-client
  - docker push lavisht22/multi-nginx
  - docker push lavisht22/multi-server
  - docker push lavisht22/multi-worker
